os:
  - linux

language:
  - minimal

services:
  - docker

# Container setup.
before_install:
  - |
    docker build -t perl6-ci - <<EOF
      FROM jjmerelo/test-perl6
      RUN apk add --no-cache bash
      # skip here-document terminator due to Travis silliness; produces a warning
  - docker images

env:
    global:
        regression: 0

matrix:
  fast_finish: true
  allow_failures:
      - regression: 1

  include:
    -
      name: "Tests"
      script: |
        docker run -t \
          --name container-env \
          --volume "$TRAVIS_BUILD_DIR":/test \
          --entrypoint bash \
          perl6-ci -c '
            # fail on first error
            set -Eeuo pipefail

            # no testing the dependencies
            zef install --/test --deps-only .

            # run tests and test installation
            zef install .
          '

    -
      name: "HPM Regression Testing"
      regression: 1
      script: |
        docker run -t \
          --name container-env \
          --volume "$TRAVIS_BUILD_DIR":/test \
          --entrypoint bash \
          perl6-ci -c '
            # fail on first error
            set -Eeuo pipefail

            # no testing the dependencies
            zef install --/test --deps-only .

            # optional, for colour
            zef install --/test Terminal::ANSIColor || true

            # install, no testing
            zef install --/test .

            # fetch & prepare HPM
            HPM_0_4_5=https://github.com/arkhometha/Historical-Project-Mod/archive/v0.4.5.2.zip
            wget -O HPM.zip "$HPM_0_4_5"
            unzip -q HPM.zip
            mv Historical-Project-Mod-0.4.5.2 HPM
            cat >hpm.whitelist <<EOF
              news/news_fake_default.txt
        EOF

            # run regression test
            vic2-companion --heartbeat --whitelist=hpm.whitelist --base=HPM/HPM .
          '

    -
      name: "HFM Regression Testing"
      regression: 1
      script: |
        docker run -t \
          --name container-env \
          --volume "$TRAVIS_BUILD_DIR":/test \
          --entrypoint bash \
          perl6-ci -c '
            # fail on first error
            set -Eeuo pipefail

            # no testing the dependencies
            zef install --/test --deps-only .

            # optional, for colour
            zef install --/test Terminal::ANSIColor || true

            # install, no testing
            zef install --/test .

            fetch_single_commit()
            {
              [ "$#" -eq 3 ] || die "invalid number of arguments"
              dest="$1"
              repo="$2"
              rev="$3"

              mkdir "$dest" && pushd "$dest"

              git init \
                && git remote add origin "$repo" \
                && git fetch --depth 1 origin "$rev" \
                && git reset --hard FETCH_HEAD

              popd
            }

            # fetch & prepare HFM
            HFM_1_27_F=38ca75c40063e08cbf696140e0ea68d76e6ace9d
            fetch_single_commit HFM https://github.com/SighPie/HFM.git "$HFM_1_27_F"
            cat >hfm.whitelist <<EOF
              history/countries/GRE - Greece.txt
              map/province_flag_sprites/kiel_canal.txt
              map/province_flag_sprites/suez_canal.txt
        EOF

            # run regression test
            vic2-companion --heartbeat --whitelist=hfm.whitelist --base=HFM/HFM .
          '
